FROM python:3.12.3

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

# update pip globally within the container
RUN python3 -m pip install --upgrade pip
# download dependencies to the image and container
RUN python3 -m pip install -r requirements.txt

# run the FlaskAPI app within uvicorn
CMD [ "uvicorn", "main:app", "--host", "0.0.0.0"]